name: Get User/Channel Info
description: Get information about the user and channel command is being run from
envvars: []
dependencies: []
help: "!bashbot info"
trigger: info
location: /bashbot/vendor/bashbot/examples/info
command:
  - "./get-info.sh"
parameters: []
log: true
ephemeral: false
response: code
permissions:
  - all