name: Get Bashbot Version
description: Displays the currently running version of Bashbot
envvars: []
dependencies: []
help: "!bashbot version"
trigger: version
location: /bashbot/vendor/bashbot/examples/version
command:
- "./get-version.sh"
parameters: []
log: true
ephemeral: false
response: code
permissions:
- all