name: Trigger a Github Action
description: Triggers an example Github Action job by repository dispatch
envvars:
  - GIT_TOKEN
dependencies: []
help: "!bashbot trigger-github-action"
trigger: trigger-github-action
location: /bashbot/vendor/bashbot/examples/trigger-github-action
command:
  - "export REPO_OWNER=mathew-fleisch"
  - "&& export REPO_NAME=bashbot"
  - "&& export SLACK_CHANNEL=${TRIGGERED_CHANNEL_ID}"
  - "&& export SLACK_USERID=${TRIGGERED_USER_ID}"
  - "&& echo \"Running this example github action: https://github.com/${REPO_OWNER}/${REPO_NAME}/blob/main/.github/workflows/example-bashbot-github-action.yaml\""
  - "&& ./trigger.sh"
parameters: []
log: true
ephemeral: false
response: text
permissions:
  - GPFMM5MD2