apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.botname }}-configmap
  namespace: {{ .Values.namespace }}
data:
  {{- if index .Values "config.yaml" }}
  config.yaml: |
{{ index .Values "config.yaml" | indent 3 }}
  .tool-versions: |
{{ index .Values ".tool-versions" | indent 3 }}
  {{- end }}
