# Name:        build-release.yaml
# Author:      Mathew Fleisch <mathew.fleisch@gmail.com>
# Description: This action will build and push go-binaries, when triggered by
#              pushing a new git tag (that starts with the letter 'v').
name: Build Bashbot Go Binaries
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release Bashbot Binaries
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Bashbot source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - 
        name: Install Golang via asdf
        uses: asdf-vm/actions/install@v1
        with:
          tool_versions: golang 1.19.4
      -
        name: Build go-binaries
        run: |
          asdf global golang 1.19.4
          make go-setup
          make go-build-cross-compile
          echo "Go-Binaries created: $(ls bin -alF)"

      -
        name: Cut Github Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GIT_TOKEN }}
          allowUpdates: true
          artifacts: "bin/*"




