# Name:        example-notify-slack.yaml
# Author:      Mathew Fleisch <mathew.fleisch@gmail.com>
# Description: This action demonstrates how to trigger a Slack Notification from Bashbot.
name: Example Bashbot Notify Slack
on:
  repository_dispatch:
    types:
      - trigger-slack-notify

jobs:
  build:
    name: Example Bashbot Notify Slack
    runs-on: ubuntu-latest
    steps:
      - 
        name: Install Bashbot via asdf
        uses: asdf-vm/actions/install@v1
        with:
          tool_versions: bashbot 2.0.3
      -
        name: Send Slack Message With Bashbot Binary
        env:
          BASHBOT_CONFIG_FILEPATH: ./config.yaml
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
        run: |
          cat <<EOF > $BASHBOT_CONFIG_FILEPATH
          admins:
            - trigger: bashbotexample
              appName: Bashbot Notify Example
              userIds:
                - "UP3BBQX34"
              privateChannelId: "GPFMM5MD2"
              logChannelId: "CPJ1NFPL7"
          messages: []
          tools: []
          dependencies: []
          EOF
          bashbot send-message \
            --channel ${{ github.event.client_payload.channel }} \
            --msg "${{ github.event.client_payload.text }}"

          