# Name:        example-notify-slack.yaml
# Author:      Mathew Fleisch <mathew.fleisch@gmail.com>
# Description: This action demonstrates how to trigger a Slack Notification from Bashbot.
name: Example Bashbot Notify Slack
on:
  repository_dispatch:
    types:
      - trigger-slack-notify

jobs:
  build:
    name: Example Bashbot Notify Slack
    runs-on: ubuntu-latest
    steps:
      - 
        name: Install Bashbot via asdf
        uses: asdf-vm/actions/install@v1
        with:
          tool_versions: bashbot 1.6.15
      -
        name: Send Slack Message With Bashbot Binary
        env:
          BASHBOT_CONFIG_FILEPATH: ./config.json
          SLACK_TOKEN: ${{ secrets.RELEASE_SLACK_TOKEN }}
        run: |
          echo '{"admins":[{"trigger":"bashbotexample","appName":"Bashbot Notify Example","userIds":[""],"privateChannelId":"","logChannelId":""}],"messages":[],"tools":[],"dependencies":[]}' > $BASHBOT_CONFIG_FILEPATH
          bashbot \
            --send-message-channel ${{ github.event.client_payload.channel }} \
            --send-message-text "${{ github.event.client_payload.text }}"

          