# Name:        release.yaml
# Author:      Mathew Fleisch <mathew.fleisch@gmail.com>
# Description: This action will build and push a multi-arch docker container,
#              cross compile go-binaries and save as release artifacts,
#              and package a helm chart as gh-pages env, when triggered by
#              pushing a new git tag (that starts with the letter 'v').
name: Release Bashbot Root
on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release-root:
    name: Release Bashbot Root Container
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Bashbot source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - 
        name: Install stuff with asdf
        uses: asdf-vm/actions/install@v1
        with:
          tool_versions: |
            golang 1.19.4
            yq 4.30.6
      -
        name: Set tag environment variable
        run: |
          echo "RELEASE_VERSION=$(make version)" >> $GITHUB_ENV
          echo "RELEASE_VERSION_NO_V=$(make version)" | sed -e 's/v//g' >> $GITHUB_ENV
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_TOKEN }}
      -
        name: Build and push root container
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/bashbot:latest-root
            ghcr.io/${{ github.repository_owner }}/bashbot:${{ env.RELEASE_VERSION }}-root
            mathewfleisch/bashbot:latest-root
            mathewfleisch/bashbot:${{ env.RELEASE_VERSION }}-root
          cache-from: type=registry,ref=mathewfleisch/bashbot:latest
          cache-to: type=inline
          build-args: NRUSER=root
  